[package]
name = "diesel-database"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.6", features = ["sqlite"] }
dotenvy = "0.15.7"
libsqlite3-sys = { version = "0.35.0", features = ["bundled"] }
